Try to fix paths in clang-tidy output [DIP-356] (#117)
Not elegant, but look for bazel cache-y paths in the output of
`clang-tidy` and strip out the prefix so that errors relate back to real
files in the repository.

An example error output from before the change:
```
ERROR: /home/matt/work/clean/starling-core/public_types/BUILD.bazel:14:17: Run clang-tidy on public_types/src/snprintf.cc failed: (Exit 1): clang_tidy failed: error executing command (from target //public_types:public_types) bazel-out/k8-fastbuild/bin/external/rules_swiftnav/clang_tidy/clang_tidy external/x86_64-linux-llvm/bin/clang-tidy external/rules_swiftnav/clang_tidy/.clang-tidy ... (remaining 80 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
1543 warnings generated.
Suppressed 1558 warnings (1541 in non-user code, 16 NOLINT, 1 with check filters).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
/home/matt/.cache/bazel/_bazel_matt/88ca1cd2a9e383e37ba5e842f72d57ea/sandbox/linux-sandbox/150/execroot/starling-core/public_types/src/snprintf.cc:101:19: warning: consider replacing 'short' with 'int16' [google-runtime-int]
struct arg_traits<signed short> final {
```

And after:
```
ERROR: /home/matt/work/clean/starling-core/public_types/BUILD.bazel:14:17: Run clang-tidy on public_types/src/snprintf.cc failed: (Exit 1): clang_tidy failed: error executing command (from target //public_types:public_types) bazel-out/k8-fastbuild/bin/external/rules_swiftnav/clang_tidy/clang_tidy external/x86_64-linux-llvm/bin/clang-tidy external/rules_swiftnav/clang_tidy/.clang-tidy ... (remaining 80 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
1543 warnings generated.
Suppressed 1558 warnings (1541 in non-user code, 16 NOLINT, 1 with check filters).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
public_types/src/snprintf.cc:101:19: warning: consider replacing 'short' with 'int16' [google-runtime-int]
struct arg_traits<signed short> final {
```

Note how the first message mentions a file in `~/.cache/bazel/....`
which is helpfully deleted as soon as the command fails. By stripping
out this prefix and leaving just the relative path within the repository
then, assuming the command is run from the repository root, the path
matches the actual real file rather than bazel's copy. IDEs and other
tooling can parse out the message and trace it back to where it actually
came from